// <auto-generated />
using System;
using LojaServicos.Api.Autor.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LojaServicos.Api.Autor.Migrations
{
    [DbContext(typeof(ContextoAutor))]
    partial class ContextoAutorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LojaServicos.Api.Autor.Modelo.AutorLivro", b =>
                {
                    b.Property<int>("AutorLivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apelido")
                        .HasColumnType("text");

                    b.Property<string>("AutorLivroGuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("AutorLivroId");

                    b.ToTable("AutorLivro");
                });

            modelBuilder.Entity("LojaServicos.Api.Autor.Modelo.GrauAcademico", b =>
                {
                    b.Property<int>("GrauAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AutorLivroId")
                        .HasColumnType("integer");

                    b.Property<string>("CentroAcademico")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataGrau")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GrauAcademicoGuid")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("GrauAcademicoId");

                    b.HasIndex("AutorLivroId");

                    b.ToTable("GrauAcademico");
                });

            modelBuilder.Entity("LojaServicos.Api.Autor.Modelo.GrauAcademico", b =>
                {
                    b.HasOne("LojaServicos.Api.Autor.Modelo.AutorLivro", "AutorLivro")
                        .WithMany("ListaGrauAcademico")
                        .HasForeignKey("AutorLivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
